//apply plugin: 'com.android.library'
//apply plugin: 'com.github.dcendents.android-maven' // 添加这个
//group = 'com.github.zhouzhuo810' // 指定group，com.github.<用户名>
plugins{
    id 'com.android.library'
}

android {
    namespace 'com.zz.excel.creator'
    compileSdk 33
    defaultConfig {
        minSdk 21
        targetSdk 33
        versionCode 9
        versionName "1.8"
    }


    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }


    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    api fileTree(includes: ['*.jar'],dir: 'libs')
    implementation project(path: ":base-common")
}