plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id "kotlin-parcelize"
    id "kotlin-kapt"
    id "com.huawei.agconnect"
}

android {
    namespace 'com.marshal.base_common'
    compileSdk 34

    defaultConfig {
        minSdk 23
        targetSdk 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        multiDexEnabled true
        kapt {
            arguments {
                arg("AROUTER_MODULE_NAME",  project.getName())
            }
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding = true
    }

}

dependencies {
    api files('libs/jxl.jar')

    api deps.android.appcompat
    api deps.android.material
    api deps.android.constraintlayout
    api deps.android.activity_ktx
    api deps.android.fragment_ktx
    //kotlin
    api deps.android.kotlin_core_ktx
    api deps.android.kotlinx_coroutines_core
    api deps.android.kotlinx_coroutines_android
    api deps.android.lifecycle_livedata_ktx
    api deps.android.lifecycle_viewmodel_ktx
    api deps.android.lifecycle_runtime_ktx
    api deps.android.lifecycle_extensions
    api deps.android.multidex
    api deps.android.work_runtime
    api deps.android.room_runtime
    api deps.android.room_compiler
    api deps.android.room_ktx
    api deps.android.room_rxjava2
    api deps.android.room_guava

    //第三方
    api deps.support.gson
    api deps.support.glide
    annotationProcessor deps.support.glide_compiler
    api deps.support.eventbus
    api deps.support.okhttp3
    api deps.support.logging_interceptor
    api deps.support.retrofit
    api deps.support.converter_scalars
    api deps.support.converter_gson
    api deps.support.adapter_rxjava2
    api deps.support.rxjava
    api deps.support.rxandroid
    api deps.support.refresh_layout_kernel
    api deps.support.refresh_header_classics
    api deps.support.refresh_footer_classics
    api deps.support.arouter_api
    kapt deps.support.arouter_compiler
    api deps.support.mmkv
    api deps.support.immersionbar
    api deps.support.immersionbar_ktx

    api deps.support.jiguang_sdk_jpush
    api deps.support.jiguang_sdk_huawei
    api deps.support.huawei_hms_push
    api deps.support.android_picker_common
    api deps.support.android_picker_wheelview
    api deps.support.android_picker_wheelPicker

    //其中latest.release指代最新Bugly SDK版本号，也可以指定明确的版本号，例如4.0.3
    implementation 'com.tencent.bugly:crashreport:4.1.9.3'

    debugImplementation deps.support.leakcanary_android
    //releaseImplementation deps.support.leakcanary_android_no_op

}

